version: '3'
services:
  rwdb: # docker exec -it ps_name bash
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: realworld # for database creation automatically
    ports:
      - 3309:3306
    volumes:
      - "./data:/var/lib/mysql" # 数据持久化